---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  data_bags_path: test/integration/data_bags

platforms:
  - name: ubuntu-12.04
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[ucarp::default]
  - name: data_bag
    run_list:
      - recipe[ucarp::data_bag]
    attributes:
      ucarp:
        data_bag:
          cluster: test

